# Generated by Django 3.0.8 on 2020-07-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20200708_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('Fiction', 'Fiction'), ('Romantic', 'Romantic'), ('Thriller', 'Thriller'), ('Rom-Com', 'Rom-Com'), ('Classic', 'Classic'), ('LGBTQ', 'LGBTQ'), ('Non-Fiction', 'Non-Fiction')], max_length=200)),
                ('Price', models.PositiveIntegerField()),
            ],
        ),
    ]
